### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/tests/django/cache'

### ISSUE THREAD

**Issue by oduvan** [django/django-docker-box#24]
Some of the tests (not all of them) are failed with this error
```

ERROR [0.005s]: test_absolute_path (check_framework.test_caches.CheckCacheAbsolutePath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/tests/django/tests/check_framework/test_caches.py", line 103, in test_absolute_path
    self.assertEqual(check_file_based_cache_is_absolute(None), [])
  File "/tests/django/django/core/checks/caches.py", line 62, in check_file_based_cache_is_absolute
    cache = caches[alias]
  File "/tests/django/django/core/cache/__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "/tests/django/django/core/cache/__init__.py", line 54, in _create_cache
    return backend_cls(location, params)
  File "/tests/django/django/core/cache/backends/filebased.py", line 23, in __init__
    self._createdir()
  File "/tests/django/django/core/cache/backends/filebased.py", line 121, in _createdir
    os.makedirs(self._dir, 0o700, exist_ok=True)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tests/django/cache'


```

**Comment by raydeal** [comment]
Hi, if it is fixed can anyone merge it? I have exactly the same issue.
